*&---------------------------------------------------------------------*
*& Report zot_28_p_ciftsayilar
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT zot_28_p_ciftsayilar.

*Çift Sayıları Bastıran Program.
*DATA: lv_number TYPE i.
*
*    DO 100 TIMES.
*     lv_number = sy-index.
*      IF lv_number MOD 2 = 0.
*        WRITE lv_number.
*        WRITE /.
*      ENDIF.
*    ENDDO.

"-----------------
*Tek Sayıları Bastıran Program
*DATA: lv_number TYPE i.
*DO 100 TIMES.
* lv_number = sy-index.
*  IF lv_number MOD 2 = 1.
*    WRITE lv_number.
*    WRITE /.
*  ENDIF.
*ENDDO.
*-------------------------------
*EKRANA RANDOM SAYI YAZDIRAN PROGRAM
*    DATA :
*  lv_MinI TYPE I,
*  lv_MaxI TYPE I,
*  lv_RndI TYPE I,
*  lv_i TYPE I.
*
*lv_MinI = 1.
*lv_MaxI = 100.
*lv_i = 10.
*
*WHILE lv_i > 0.
*
*CALL FUNCTION 'QF05_RANDOM_INTEGER'
*  EXPORTING
*    ran_int_max = lv_MaxI
*    ran_int_min = lv_MinI
*  IMPORTING
*    ran_int = lv_RndI
*  EXCEPTIONS
*    invalid_input = 1
*    OTHERS = 2.
*
*WRITE :/ 'The Random Number Generated by QF05_RANDOM_INTEGER is : ', lv_RndI.
*
*lv_i = lv_i - 1.
*
*ENDWHILE.

DATA:
  gs_saplane TYPE saplane,
  gt_saplane TYPE TABLE OF saplane.

SELECT * FROM saplane INTO TABLE gt_saplane.

TYPE-POOLS slis.

DATA:
  gt_fieldcat TYPE slis_t_fieldcat_alv,
  gv_title TYPE lvc_title.

gv_title = 'SAP Table SAPLAsNE contents'.

CALL FUNCTION 'REUSE_ALV_FIELsDCATALOG_MERGE'
EXPORTING
  i_program_name = SY-REPID
  i_structure_name = 'SAPLANE'
CHANGING
  ct_fieldcat = gt_fieldcat.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
EXPORTING
  it_fieldcat = gt_fieldcat
  i_grid_title = gv_title
TABLES
  t_outtab = gt_saplane.
